<a href="https://colab.research.google.com/github/xfil/pyStuff/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy module**

NumPy (short for "Numerical Python") is a Python library used for working with arrays

Includes functions for linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. 



## **Lists vs Arrays**

By default Python provides Lists which are similar to arrays
However, numpy aims to provide a much faster and more efficient array structure and that can handle math opperations that cannot be applied to Lists.

These structures are essential to Data Science

To use arrays in Python they need to be imported such as from the numpy library

Contrary to Lists, arrays must be declared

https://www.w3schools.com/python/numpy/numpy_intro.asp
https://www.kaggle.com/code/ravichaubey1506/essential-numpy/notebook

In [3]:
import numpy as np # the 'as' creates an alias, now numpy can be refered simply as np

In [4]:
array = np.array(["numbers", 3, 6, 9, 12])
print (array)
print(type(array)) # the numpy array is an ndarray object

['numbers' '3' '6' '9' '12']
<class 'numpy.ndarray'>


In [5]:
# Create array with float type
np.array([10,20,30],dtype=float)

array([10., 20., 30.])

In [6]:
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
print(np.zeros((5,5)))
print(np.ones((5,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
np.full((5,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [13]:
np.linspace(0,49) # gives 10 equally spaced value between 0 and 49 - by default outputs 50 values

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

In [14]:
np.linspace(0,9,10) # define the number of output number as 10

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [15]:
np.random.random((5,5)) # Uniformly distributed random number between 0 and 1

array([[0.79139183, 0.49955771, 0.19117638, 0.03948174, 0.4749722 ],
       [0.00685714, 0.77346359, 0.76051341, 0.06686075, 0.3262516 ],
       [0.76748839, 0.60476437, 0.10966265, 0.76732205, 0.14183987],
       [0.93994383, 0.85382435, 0.24064533, 0.33556447, 0.29456516],
       [0.53206388, 0.65863283, 0.93151455, 0.68409888, 0.1121958 ]])

In [16]:
print(np.random.randint(0,10,5)) # 5 Random Integer between 0 and 10
print(np.random.randint(0,10,(5,5)))

[2 8 9 6 2]
[[7 5 0 2 4]
 [8 6 9 0 1]
 [0 9 9 7 1]
 [4 4 0 4 9]
 [0 8 9 2 9]]


In [17]:
np.random.randn(10,10) #normally distributed numbers

array([[-1.89764086,  0.55271959,  0.90024487, -1.11318942, -0.1508521 ,
        -0.89339172, -0.65182398, -0.85352388,  0.33440647,  1.99790507],
       [ 0.37905096, -0.57803856, -0.18307867,  0.3005285 ,  1.26566171,
        -1.64173129,  1.27478654, -2.20983629,  1.51756195, -0.89372768],
       [ 0.12876689, -1.94693357, -1.41307221,  0.12829031,  0.64464753,
        -1.27762423,  0.27904613,  1.48382218,  1.34260903, -1.73333999],
       [ 0.91535144,  0.81702948, -0.25712008,  0.76940381,  0.24041627,
        -0.16618064, -0.90431655, -1.46905529,  0.1564048 ,  1.46008278],
       [ 1.89636641,  1.27528919,  0.37957325, -1.33369765, -0.35186649,
        -0.55096621,  1.24774529, -0.3319259 ,  0.05656793, -0.15528337],
       [ 0.88894208, -0.518279  , -0.77703799, -1.07165137,  0.45091907,
         0.17137499, -1.16777025,  0.27275071, -0.55359284, -0.35920464],
       [ 0.4794752 , -0.45719773, -1.38325749, -0.53968264,  0.99235543,
        -1.6246141 ,  0.51583855,  2.25218392

In [24]:
# 3D array
arr3D = np.random.randint(10,size=(3,3,5))#3,3*5 matrix 
arr3D

array([[[3, 9, 5, 4, 4],
        [0, 9, 6, 7, 5],
        [6, 2, 2, 0, 4]],

       [[6, 3, 2, 1, 9],
        [3, 6, 3, 6, 7],
        [4, 7, 1, 7, 1]],

       [[9, 6, 4, 5, 2],
        [0, 3, 5, 1, 7],
        [8, 3, 1, 8, 7]]])

In [27]:
print(arr3D.shape)
print(arr3D.ndim)
print(arr3D.size)

(3, 3, 5)
3
45


array = [[[8, 3], [2, 6]], 
         [[4, 5], [3, 7]], 
         [[7, 6], [8, 2]]]

x = [[[8, 3], [2, 6]], [[4, 5], [3, 7]], [[7, 6], [8, 2]]]

y =  [[8, 3], [2, 6]] and [[4, 5], [3, 7]] and [[7, 6], [8, 2]]

z = [8, 3], [2, 6] and [4, 5], [3, 7] and [7, 6], [8, 2]


# **Array reshape**

Convert between different dimension arrays

In [36]:
arr1D = np.arange(0,12)
arr1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
arr1D.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
arr1D.reshape(1,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [39]:
arr1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
arr1D[np.newaxis,:] #add new axis - rowise

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [41]:
arr1D[:,np.newaxis] #add new axis - columnwise

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

# **Concatenate array**

In [46]:
arr1D2 = np.arange(0,20)
arr1D2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [47]:
arrConc = np.concatenate([arr1D,arr1D2]) #Combine 2 arrays - same dimensionality
arrConc

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,
        5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [51]:
arr2D = np.random.randint(0,10,(2,12)) #explain randint
arr2D

array([[1, 4, 7, 4, 8, 8, 9, 2, 0, 5, 8, 7],
       [2, 8, 3, 7, 9, 2, 6, 5, 6, 7, 0, 0]])

In [52]:
arrConc2 = np.vstack([arr1D,arr2D]) #combine 2 arrays with different dimensionality but dimension of first axis must be equal (12 in this case) - in numpy: rows - axis 0, columns axis 1
arrConc2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 1,  4,  7,  4,  8,  8,  9,  2,  0,  5,  8,  7],
       [ 2,  8,  3,  7,  9,  2,  6,  5,  6,  7,  0,  0]])

Numpy axes:
https://www.sharpsightlabs.com/blog/numpy-axes-explained/

In [53]:
x= np.array([[55], [46]])
np.hstack([arr2D,x])

array([[ 1,  4,  7,  4,  8,  8,  9,  2,  0,  5,  8,  7, 55],
       [ 2,  8,  3,  7,  9,  2,  6,  5,  6,  7,  0,  0, 46]])

# **Split array**

In [54]:
np.split(arr1D,[2,5]) 

[array([0, 1]), array([2, 3, 4]), array([ 5,  6,  7,  8,  9, 10, 11])]

In [56]:
upper,lower=np.vsplit(arr2D,[1])
print(upper)
print("\n")
print(lower)

[[1 4 7 4 8 8 9 2 0 5 8 7]]


[[2 8 3 7 9 2 6 5 6 7 0 0]]


In [57]:
upper,lower=np.hsplit(arr2D,[6])
print(upper)
print("\n")
print(lower)

[[1 4 7 4 8 8]
 [2 8 3 7 9 2]]


[[9 2 0 5 8 7]
 [6 5 6 7 0 0]]


Funções

In [64]:
arr1D = np.arange(5)
print(arr1D)
np.add(arr1D,3) #add +3 to each position

[0 1 2 3 4]


array([3, 4, 5, 6, 7])

In [69]:
arr1D2 = np.empty(5)
print(arr1D)
np.multiply(arr1D,10,out=arr1D2)
#print(arr1D2)

[0 1 2 3 4]


array([ 0., 10., 20., 30., 40.])

In [71]:
arr1D3 = np.zeros(15)
print(arr1D3)
np.power(3,arr1D,out=arr1D3[::3])
print(arr1D3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 1.  0.  0.  3.  0.  0.  9.  0.  0. 27.  0.  0. 81.  0.  0.]


In [72]:
np.add.reduce(arr1D)

10

In [77]:
arr1D=np.arange(1,11)
arr1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
np.add.reduce(arr1D)

55

In [79]:
np.multiply.reduce(arr1D)

3628800

In [80]:
np.add.accumulate(arr1D)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [82]:
print(arr1D)
np.cumsum(arr1D)  #Cummulative sum

[ 1  2  3  4  5  6  7  8  9 10]


array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [83]:
np.cumprod(arr1D)

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800])

In [84]:
np.multiply.outer(arr1D,arr1D)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [85]:
print(arr2D)
arr2D.sum()

[[1 4 7 4 8 8 9 2 0 5 8 7]
 [2 8 3 7 9 2 6 5 6 7 0 0]]


118

In [86]:
arr2D.sum(axis=0) # sum all values in each column

array([ 3, 12, 10, 11, 17, 10, 15,  7,  6, 12,  8,  7])

In [87]:
arr2D.sum(axis=1) # sum all values in each row

array([63, 55])